### ISSUE TITLE
Nan loss

### ISSUE THREAD

**Issue by LI945** [RAIVNLab/STR#1]

**Comment by LI945** [comment]
Hi, 
Thanks for your code. STR is a nice work for pruning. But when I run 
python main.py --config configs/largescale/mobilenetv1-str.yaml --multigpu 0,1
I got a Nan loss and 0 Acc. I set batchsize as 64 with two 2080Ti gpus.

**Comment by adityakusupati** [comment]
@LI945 thanks for your interest. The weight decay hparam has to change according to the batch size as the number of gradient steps becomes disproportionate. Also, it shouldn't happen immediately but rather after hitting some good accuracy. This essentially means you are pruning all the weights out to zero. 

A thumb rule is decrease weight decay when decreasing batch size.
