### ISSUE TITLE
MobileNet v2

### ISSUE THREAD

**Issue by gbc8181** [RAIVNLab/STR#3]
Hi,

Does STR support MobileNet v2? 

Thanks

**Comment by adityakusupati** [comment]
Hi,

STR supports any model. You just need to define the model here: https://github.com/RAIVNLab/STR/tree/master/models and just use it like any other model. You might have to play around a bit to figure out the right settings and once that is done, it will be very easy to navigate. 

You can also, just take the STRConv: https://github.com/RAIVNLab/STR/blob/master/utils/conv_type.py and use it in your code as it is overloaded over nn.conv2d.

Hope this helps.
