### ISSUE TITLE
view size error

### ISSUE THREAD

**Issue by junhyukso** [RAIVNLab/STR#4]
Hi, Thanks for your great work!

I just ran the evaluation code, but i found the error
```
...
  File "/home/goqhadl9298/STR/utils/eval_utils.py", line 18, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
can you please check it?

**Comment by adityakusupati** [comment]
Hi,

You can safely replace view(-1) with reshape(-1) and it should work. This is dependent on how tensor memory is allocated and not a programming thing. 

Else you can call .contiguous() before view

Let me know if this fixes it :)

**Comment by junhyukso** [comment]
Hi @adityakusupati , 
This works, Thanks!
